export { default as IconAccreditation } from './icons/IconAccreditation.vue'
export { default as IconActivity } from './icons/IconActivity.vue'
export { default as IconAdd } from './icons/IconAdd.vue'
export { default as IconAdmin } from './icons/IconSliders.vue' // aliasing IconSlider
export { default as IconAlcohol } from './icons/IconAlcohol.vue'
export { default as IconArrow } from './icons/IconArrow.vue'
export { default as IconAttachment } from './icons/IconAttachment.vue'
export { default as IconAttention } from './icons/IconError.vue' // aliasing IconError
export { default as IconAvatar } from './icons/IconAvatar.vue'
export { default as IconBlock } from './icons/IconBlock.vue'
export { default as IconBudget } from './icons/IconBudget.vue'
export { default as IconBurger } from './icons/IconBurger.vue'
export { default as IconCalendar } from './icons/IconCalendar.vue'
export { default as IconCalendarDetailed } from './icons/IconCalendarDetailed.vue'
export { default as IconCamera } from './icons/IconCamera.vue'
export { default as IconCheck } from './icons/IconComplete.vue' // aliasing IconComplete
export { default as IconChevron } from './icons/IconChevron.vue'
export { default as IconCircleClose } from './icons/IconCircleClose.vue'
export { default as IconClock } from './icons/IconClock.vue'
export { default as IconClose } from './icons/IconClose.vue'
export { default as IconCompanyInfo } from './icons/IconCompanyInfo.vue'
export { default as IconComplete } from './icons/IconComplete.vue'
export { default as IconContractor } from './icons/IconContractor.vue'
export { default as IconDashboard } from './icons/IconDashboard.vue'
export { default as IconDelete } from './icons/IconClose.vue' // aliasing IconClose
export { default as IconEdit } from './icons/IconEdit.vue'
export { default as IconError } from './icons/IconError.vue'
export { default as IconEvent } from './icons/IconEvent.vue'
export { default as IconEventInfo } from './icons/IconEventInfo.vue'
export { default as IconEventLogs } from './icons/IconHospital.vue' // aliasing IconHospital
export { default as IconExcel } from './icons/IconExcel.vue'
export { default as IconFile } from './icons/IconFile.vue'
export { default as IconFlag } from './icons/IconFlag.vue'
export { default as IconGrid } from './icons/IconGrid.vue'
export { default as IconHamburger } from './icons/IconBurger.vue'  // aliasing IconBurger
export { default as IconHome } from './icons/IconHome.vue'
export { default as IconHospital } from './icons/IconHospital.vue'
export { default as IconLoading } from './icons/IconLoading.vue'
export { default as IconLocation } from './icons/IconLocation.vue'
export { default as IconLocationPin } from './icons/IconLocationPin.vue'
export { default as IconMoreHorizontal } from './icons/IconMoreHorizontal.vue'
export { default as IconMusic } from './icons/IconMusic.vue'
export { default as IconNotification } from './icons/IconNotification.vue'
export { default as IconOrganizer } from './icons/IconOrganizer.vue'
export { default as IconQuestionMark } from './icons/IconQuestionMark.vue'
export { default as IconRegulations } from './icons/IconRegulations.vue'
export { default as IconRisk } from './icons/IconRisk.vue'
export { default as IconSearch } from './icons/IconSearch.vue'
export { default as IconSearchAlt } from './icons/IconSearchAlt.vue'
export { default as IconSettings } from './icons/IconSettings.vue'
export { default as IconSliders } from './icons/IconSliders.vue'
export { default as IconSort } from './icons/IconSort.vue'
export { default as IconStar } from './icons/IconStar.vue'
export { default as IconSuccess } from './icons/IconSuccess.vue'
export { default as IconTeamManagement } from './icons/IconUsers.vue' // aliasing IconUsers
export { default as IconTrash } from './icons/IconTrash.vue'
export { default as IconUpload } from './icons/IconUpload.vue'
export { default as IconUserCheck } from './icons/IconUserCheck.vue'
export { default as IconUsers } from './icons/IconUsers.vue'
export { default as IconValid } from './icons/IconSuccess.vue' // aliasing IconSuccess
export { default as IconWarning } from './icons/IconWarning.vue'
export { default as IconWeather } from './icons/IconWeather.vue'
